import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import useStore from '../store/tempStore';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  const { bears, increase } = useStore();
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={''}>
        <div className="card w-96 bg-base-100 shadow-xl">
          <figure>
            <Image
              src="https://api.lorem.space/image/shoes?w=400&h=225"
              alt="Shoes"
              width={400}
              height={225}
            />
          </figure>
          <div className="card-body">
            <h2 className="card-title">Shoes!</h2>
            <p>If a dog chews shoes whose shoes does he choose?</p>
            <p>Bears in town {bears}</p>
            <div className="card-actions justify-end">
              <button className="btn btn-primary" onClick={() => increase(1)}>
                Buy Now
              </button>
            </div>
          </div>
        </div>
      </main>

      <footer className={''}></footer>
    </div>
  );
};

export default Home;
